-- =====================================================
-- BARRELVERSE COMPLETE DATA INSERT
-- Run this AFTER the schema is created
-- Total: 500+ trivia questions, 100+ spirits
-- =====================================================

-- BOURBON TRIVIA - 100 Questions
INSERT INTO bv_trivia_questions (category, difficulty, question, correct_answer, wrong_answers, proof_reward, explanation) VALUES
-- EASY (25)
('bourbon', 'easy', 'What US state produces 95% of the world''s bourbon?', 'Kentucky', '["Tennessee", "Virginia", "Texas"]', 10, 'Kentucky is the heartland of bourbon production.'),
('bourbon', 'easy', 'What grain must make up at least 51% of bourbon''s mash bill?', 'Corn', '["Rye", "Wheat", "Barley"]', 10, 'By law, bourbon must be at least 51% corn.'),
('bourbon', 'easy', 'What type of container must bourbon be aged in?', 'New charred oak barrel', '["Used wine barrel", "Steel tank", "Clay pot"]', 10, 'New charred oak barrels are required by law.'),
('bourbon', 'easy', 'What country must bourbon be made in?', 'United States', '["Scotland", "Ireland", "Canada"]', 10, 'Bourbon is America''s native spirit.'),
('bourbon', 'easy', 'What color is bourbon?', 'Amber/Brown', '["Clear", "Green", "Blue"]', 10, 'Bourbon gets its color from barrel aging.'),
('bourbon', 'easy', 'Which bourbon brand features a red wax seal?', 'Maker''s Mark', '["Jim Beam", "Wild Turkey", "Knob Creek"]', 10, 'Maker''s Mark is famous for its hand-dipped red wax.'),
('bourbon', 'easy', 'What does "straight bourbon" mean?', 'Aged at least 2 years', '["No water added", "Single barrel", "100 proof"]', 10, 'Straight bourbon must be aged minimum 2 years.'),
('bourbon', 'easy', 'What is the most common bottle size for bourbon?', '750ml', '["500ml", "1 liter", "375ml"]', 10, '750ml is the standard bottle size.'),
('bourbon', 'easy', 'What family owns the Jim Beam brand?', 'Beam family', '["Brown family", "Smith family", "Jones family"]', 10, 'Seven generations of Beams have made bourbon.'),
('bourbon', 'easy', 'What does "proof" measure?', 'Alcohol content', '["Age", "Quality", "Price"]', 10, 'Proof is twice the alcohol by volume percentage.'),
('bourbon', 'easy', 'What is bourbon typically served in?', 'Rocks glass', '["Wine glass", "Shot glass", "Champagne flute"]', 10, 'A rocks glass or tumbler is traditional.'),
('bourbon', 'easy', 'Which bourbon has a horse on its label?', 'Blanton''s', '["Maker''s Mark", "Woodford Reserve", "Knob Creek"]', 10, 'Blanton''s features a horse and jockey stopper.'),
('bourbon', 'easy', 'What is the main flavor note in most bourbons?', 'Vanilla', '["Lemon", "Mint", "Pepper"]', 10, 'Vanilla comes from the charred oak barrels.'),
('bourbon', 'easy', 'What does "small batch" generally mean?', 'Blend of select barrels', '["Single barrel", "Under 100 bottles", "Aged less than 2 years"]', 10, 'Small batch combines a limited number of barrels.'),
('bourbon', 'easy', 'What river runs through bourbon country?', 'Kentucky River', '["Mississippi River", "Ohio River", "Cumberland River"]', 10, 'The Kentucky River flows through prime bourbon territory.'),
('bourbon', 'easy', 'What is Wild Turkey''s signature proof?', '101 proof', '["80 proof", "90 proof", "120 proof"]', 10, 'Wild Turkey 101 is their flagship bourbon.'),
('bourbon', 'easy', 'What does "sour mash" refer to?', 'Using leftover mash from previous batch', '["Adding lemon", "Spoiled bourbon", "Low quality"]', 10, 'Sour mash ensures consistency between batches.'),
('bourbon', 'easy', 'What is the legal minimum ABV for bourbon entering the barrel?', '62.5%', '["40%", "50%", "70%"]', 10, 'Bourbon cannot enter the barrel above 125 proof (62.5% ABV).'),
('bourbon', 'easy', 'Which bourbon brand is known for its square bottle?', 'Knob Creek', '["Buffalo Trace", "Evan Williams", "Old Crow"]', 10, 'Knob Creek has a distinctive square bottle.'),
('bourbon', 'easy', 'What is added to bourbon to lower the proof before bottling?', 'Water', '["Sugar", "Caramel", "Alcohol"]', 10, 'Only water can be added to bourbon.'),
('bourbon', 'easy', 'What is the name of Buffalo Trace''s free tour?', 'Trace Tour', '["Heritage Tour", "Bourbon Trail", "Distillery Walk"]', 10, 'Buffalo Trace offers free daily tours.'),
('bourbon', 'easy', 'What shape are most bourbon barrels?', 'Barrel-shaped (bilge)', '["Square", "Rectangular", "Triangular"]', 10, 'Traditional barrel shape with curved sides.'),
('bourbon', 'easy', 'What is bourbon called before it''s aged?', 'White dog', '["Clear whiskey", "Baby bourbon", "Raw spirit"]', 10, 'Unaged bourbon is called white dog or white lightning.'),
('bourbon', 'easy', 'How many gallons does a standard bourbon barrel hold?', '53 gallons', '["30 gallons", "100 gallons", "75 gallons"]', 10, 'A standard barrel holds 53 gallons.'),
('bourbon', 'easy', 'What color is a charred bourbon barrel inside?', 'Black', '["Brown", "Red", "Natural wood"]', 10, 'Charring creates a black carbon layer.'),
-- MEDIUM (40)
('bourbon', 'medium', 'What year did Congress declare bourbon a distinctive product of the US?', '1964', '["1950", "1976", "1933"]', 15, 'Senate Resolution 19 of 1964 made it official.'),
('bourbon', 'medium', 'What is the "angel''s share"?', 'Whiskey lost to evaporation during aging', '["First pour from barrel", "Distiller''s sample", "Broken bottles"]', 15, 'About 2-4% evaporates each year.'),
('bourbon', 'medium', 'Which distillery produces Pappy Van Winkle?', 'Buffalo Trace', '["Heaven Hill", "Jim Beam", "Wild Turkey"]', 15, 'Buffalo Trace makes all Van Winkle bourbons.'),
('bourbon', 'medium', 'What is the mashbill of a "wheated" bourbon?', 'Uses wheat instead of rye as secondary grain', '["100% wheat", "No corn", "Extra barley"]', 15, 'Wheated bourbons are softer and sweeter.'),
('bourbon', 'medium', 'What proof must bourbon be distilled below?', '160 proof', '["140 proof", "180 proof", "190 proof"]', 15, 'Cannot exceed 160 proof off the still.'),
('bourbon', 'medium', 'What is a "single barrel" bourbon?', 'Bourbon from one specific barrel', '["Made by one person", "One grain", "One day production"]', 15, 'Each bottle comes from an individual barrel.'),
('bourbon', 'medium', 'What is "bottled in bond" bourbon?', 'Made at one distillery, one season, aged 4+ years at 100 proof', '["Highest quality", "Most expensive", "Oldest bourbon"]', 15, 'The Bottled in Bond Act of 1897 established these standards.'),
('bourbon', 'medium', 'Which bourbon county is named after a French royal family?', 'Bourbon County', '["Fayette County", "Jefferson County", "Scott County"]', 15, 'Named after the French House of Bourbon.'),
('bourbon', 'medium', 'What temperature causes bourbon to expand into the wood?', 'Hot summer temperatures', '["Cold winter", "Room temperature", "Spring weather"]', 15, 'Heat pushes bourbon into the charred wood.'),
('bourbon', 'medium', 'What is the maximum proof bourbon can be barreled at?', '125 proof', '["100 proof", "150 proof", "140 proof"]', 15, '125 proof (62.5% ABV) is the legal maximum.'),
('bourbon', 'medium', 'What does "char level 4" mean?', 'Heaviest char, also called alligator char', '["Lightest char", "Medium char", "No char"]', 15, 'Level 4 creates deep cracks resembling alligator skin.'),
('bourbon', 'medium', 'Which famous bourbon uses a wheat-forward mashbill?', 'Maker''s Mark', '["Wild Turkey", "Four Roses", "Old Forester"]', 15, 'Maker''s Mark uses red winter wheat.'),
('bourbon', 'medium', 'What is the Kentucky Bourbon Trail?', 'A tourism trail connecting distilleries', '["A hiking path", "A river route", "A highway"]', 15, 'The trail includes major Kentucky distilleries.'),
('bourbon', 'medium', 'How many distilleries are on the main Kentucky Bourbon Trail?', '18', '["5", "10", "25"]', 15, 'The official trail has 18 member distilleries.'),
('bourbon', 'medium', 'What grain provides spiciness in bourbon?', 'Rye', '["Corn", "Wheat", "Barley"]', 15, 'Rye adds spicy, peppery notes.'),
('bourbon', 'medium', 'What is the purpose of the copper in stills?', 'Removes sulfur compounds', '["Adds flavor", "Faster distillation", "Better color"]', 15, 'Copper catalyzes reactions that remove sulfur.'),
('bourbon', 'medium', 'Which brand produces Booker''s bourbon?', 'Jim Beam', '["Buffalo Trace", "Heaven Hill", "Wild Turkey"]', 15, 'Booker''s is Jim Beam''s premium unfiltered bourbon.'),
('bourbon', 'medium', 'What is "chill filtering"?', 'Cooling bourbon to remove fatty acids', '["Adding ice", "Cold storage", "Freeze distillation"]', 15, 'Chill filtering prevents cloudiness when cold.'),
('bourbon', 'medium', 'What is barrel entry proof?', 'The proof when bourbon enters the barrel', '["Final bottle proof", "Distillation proof", "Fermentation strength"]', 15, 'Lower entry proof means more flavor from wood.'),
('bourbon', 'medium', 'What family founded Woodford Reserve distillery?', 'The Brown family', '["The Beam family", "The Samuels family", "The Russell family"]', 15, 'Brown-Forman owns Woodford Reserve.'),
('bourbon', 'medium', 'What is "rickhouse"?', 'A warehouse for aging bourbon barrels', '["Distillation building", "Bottling facility", "Grain storage"]', 15, 'Rickhouses store barrels during aging.'),
('bourbon', 'medium', 'How does warehouse location affect bourbon flavor?', 'Higher floors age faster due to heat', '["No effect", "Lower floors age faster", "Middle is best"]', 15, 'Heat rises, causing more wood interaction on upper floors.'),
('bourbon', 'medium', 'What percentage of bourbon''s flavor comes from the barrel?', 'About 60-70%', '["10-20%", "30-40%", "90-100%"]', 15, 'The barrel contributes most of bourbon''s flavor and color.'),
('bourbon', 'medium', 'What was the Whiskey Rebellion of 1794?', 'Tax protest by farmers', '["Civil War battle", "Prohibition movement", "Labor strike"]', 15, 'Farmers protested federal whiskey taxes.'),
('bourbon', 'medium', 'Which bourbon is aged in honey barrels for finishing?', 'Barrell Bourbon', '["Maker''s Mark", "Jim Beam", "Buffalo Trace"]', 15, 'Barrell offers various barrel-finished bourbons.'),
('bourbon', 'medium', 'What is the "heads" in distillation?', 'First portion of distillate, discarded', '["Best part", "Final portion", "Middle section"]', 15, 'Heads contain harsh, unwanted compounds.'),
('bourbon', 'medium', 'What is the "tails" in distillation?', 'Last portion, often redistilled', '["First portion", "Best portion", "Discarded entirely"]', 15, 'Tails have heavier compounds and less alcohol.'),
('bourbon', 'medium', 'What is the "heart" or "hearts" in distillation?', 'The best middle portion kept for aging', '["First run", "Last run", "Entire distillate"]', 15, 'Hearts have the best flavor compounds.'),
('bourbon', 'medium', 'What does NAS mean on a bourbon label?', 'No Age Statement', '["Not Available for Sale", "National Association Standard", "New American Spirit"]', 15, 'NAS bourbons don''t disclose their age.'),
('bourbon', 'medium', 'What is a "honey barrel"?', 'An exceptionally good barrel', '["Barrel with honey added", "First barrel made", "Smallest barrel"]', 15, 'Distillers identify standout barrels as honey barrels.'),
('bourbon', 'medium', 'Which distillery is the oldest operating in Kentucky?', 'Buffalo Trace', '["Maker''s Mark", "Jim Beam", "Wild Turkey"]', 15, 'Buffalo Trace has operated since 1775.'),
('bourbon', 'medium', 'What is "barrel proof" bourbon?', 'Bottled at the proof it comes out of the barrel', '["Highest possible proof", "Exactly 100 proof", "Double distilled"]', 15, 'No water is added to barrel proof bourbon.'),
('bourbon', 'medium', 'How long must bourbon be aged to be called "straight"?', '2 years minimum', '["1 year", "4 years", "6 years"]', 15, 'Under 4 years requires an age statement.'),
('bourbon', 'medium', 'What is Four Roses known for?', 'Using 10 different recipes', '["Square bottles", "Red wax", "White labels"]', 15, 'Four Roses uses 2 mashbills and 5 yeast strains.'),
('bourbon', 'medium', 'What is "mingling" in bourbon production?', 'Combining barrels before bottling', '["Adding water", "Filtering", "Distilling twice"]', 15, 'Mingling creates consistent flavor profiles.'),
('bourbon', 'medium', 'What famous cocktail was invented in Louisville?', 'Old Fashioned', '["Manhattan", "Mint Julep", "Whiskey Sour"]', 15, 'The Old Fashioned originated at the Pendennis Club.'),
('bourbon', 'medium', 'What is the traditional bourbon cocktail for the Kentucky Derby?', 'Mint Julep', '["Old Fashioned", "Manhattan", "Whiskey Sour"]', 15, 'Over 120,000 Mint Juleps are served at the Derby.'),
('bourbon', 'medium', 'What company owns the most bourbon brands?', 'Beam Suntory', '["Brown-Forman", "Sazerac", "Heaven Hill"]', 15, 'Beam Suntory owns Jim Beam, Maker''s Mark, and more.'),
('bourbon', 'medium', 'What does "double oaked" mean?', 'Finished in a second new oak barrel', '["Aged twice as long", "Two barrels mixed", "Oak chips added"]', 15, 'Double oaking adds extra wood influence.'),
-- HARD (25)
('bourbon', 'hard', 'What is the Lincoln County Process?', 'Filtering through maple charcoal before aging', '["Kentucky aging law", "Federal tax rule", "Barrel treatment"]', 20, 'This process distinguishes Tennessee whiskey from bourbon.'),
('bourbon', 'hard', 'What is the typical fermentation time for bourbon mash?', '3-5 days', '["1 day", "2 weeks", "1 month"]', 20, 'Fermentation converts sugars to alcohol.'),
('bourbon', 'hard', 'What yeast strain is famous at Four Roses?', 'V, K, O, Q, and F strains', '["Champagne yeast", "Bread yeast", "Wild yeast only"]', 20, 'Each yeast creates different flavor profiles.'),
('bourbon', 'hard', 'What is the approximate evaporation loss per year in Kentucky?', '2-4%', '["Less than 1%", "10-15%", "20-25%"]', 20, 'Kentucky''s climate causes moderate evaporation.'),
('bourbon', 'hard', 'What law requires age statements on bourbon under 4 years?', 'Federal Standards of Identity', '["Kentucky State Law", "TTB Regulation 5.40", "Bourbon Act of 1964"]', 20, 'Federal law mandates age disclosure for young bourbons.'),
('bourbon', 'hard', 'What is "sweet mash" fermentation?', 'Using fresh yeast without backset', '["Adding sugar", "Honey-flavored", "Short fermentation"]', 20, 'Sweet mash doesn''t use previous batch''s stillage.'),
('bourbon', 'hard', 'What temperature does bourbon typically ferment at?', '77-86°F', '["50-60°F", "100-110°F", "32-40°F"]', 20, 'Controlled temperatures produce cleaner fermentation.'),
('bourbon', 'hard', 'What is "setback" or "backset" in bourbon making?', 'Spent mash liquid added to new fermentation', '["Rejected bourbon", "Overflow liquid", "Cleaning solution"]', 20, 'Backset helps control pH and adds consistency.'),
('bourbon', 'hard', 'What percentage of bourbon''s final flavor comes from fermentation?', 'About 30%', '["5%", "60%", "90%"]', 20, 'Fermentation creates many flavor compounds.'),
('bourbon', 'hard', 'What is the "white dog" proof typically?', '125-135 proof', '["80 proof", "100 proof", "160 proof"]', 20, 'New make spirit before dilution for barreling.'),
('bourbon', 'hard', 'What wood species must bourbon barrels be made from?', 'Oak (typically American white oak)', '["Any hardwood", "Pine", "Maple"]', 20, 'American white oak (Quercus alba) is standard.'),
('bourbon', 'hard', 'What is the "devil''s cut"?', 'Bourbon absorbed into the barrel wood', '["Spilled bourbon", "First distillation", "Evaporated spirit"]', 20, 'Jim Beam markets a bourbon using extracted devil''s cut.'),
('bourbon', 'hard', 'How many times is bourbon typically distilled?', 'Twice (usually)', '["Once", "Three times", "Four times"]', 20, 'Column still then doubler/thumper is common.'),
('bourbon', 'hard', 'What is a "thumper" in bourbon distillation?', 'Secondary distillation vessel', '["Mixing tank", "Barrel seal tester", "Quality control device"]', 20, 'The thumper provides additional distillation.'),
('bourbon', 'hard', 'What is the typical pH of bourbon mash?', '4.0-5.0', '["7.0 neutral", "2.0-3.0", "8.0-9.0"]', 20, 'Acidic pH prevents bacterial contamination.'),
('bourbon', 'hard', 'What compound gives bourbon its vanilla flavor?', 'Vanillin from lignin in oak', '["Added vanilla extract", "Corn sugars", "Yeast byproduct"]', 20, 'Heat breaks down lignin into vanillin.'),
('bourbon', 'hard', 'What is "barrel dumping day"?', 'When barrels are emptied for bottling', '["Disposing bad barrels", "Tax payment day", "Inventory count"]', 20, 'Distilleries schedule dumping for bottling runs.'),
('bourbon', 'hard', 'What enzyme converts starch to sugar in mashing?', 'Amylase', '["Lipase", "Protease", "Lactase"]', 20, 'Amylase from malted barley breaks down starches.'),
('bourbon', 'hard', 'What is the "low wines" in bourbon production?', 'First distillation output before second run', '["Cheap bourbon", "Diluted bourbon", "Young bourbon"]', 20, 'Low wines are then redistilled to higher proof.'),
('bourbon', 'hard', 'What causes the red layer in bourbon barrels?', 'Caramelized wood sugars', '["Blood from cooperage", "Rust", "Added coloring"]', 20, 'The red layer contains flavor compounds.'),
('bourbon', 'hard', 'What is the congener profile of bourbon compared to vodka?', 'Much higher in congeners', '["Same level", "Lower", "No congeners"]', 20, 'Congeners are flavor compounds from fermentation.'),
('bourbon', 'hard', 'What is the typical grain-to-water ratio in bourbon mashing?', '1:3 to 1:4', '["1:1", "1:10", "1:20"]', 20, 'This ratio optimizes starch conversion.'),
('bourbon', 'hard', 'What percentage of a barrel''s volume is legally considered a "barrel"?', 'No legal definition of size', '["Exactly 53 gallons", "50-60 gallons", "40 gallons minimum"]', 20, 'Standard is 53 gallons but not legally required.'),
('bourbon', 'hard', 'What is "dosage" sometimes used in bourbon finishing?', 'Adding small amounts of other spirits or wine', '["Sugar addition", "Water addition", "Yeast addition"]', 20, 'Some craft producers experiment with dosage.'),
('bourbon', 'hard', 'What wood compound creates bourbon''s spicy notes?', 'Eugenol', '["Tannins", "Vanillin", "Lactones"]', 20, 'Eugenol provides clove-like spiciness.'),
-- EXPERT (10)
('bourbon', 'expert', 'What is the chemical process that creates color during charring?', 'Maillard reaction and caramelization', '["Oxidation only", "Fermentation", "Distillation"]', 25, 'Multiple reactions create color and flavor compounds.'),
('bourbon', 'expert', 'What lactone compound gives bourbon coconut notes?', 'Whiskey lactone (cis-3-methyl-4-octanolide)', '["Vanillin", "Eugenol", "Furfural"]', 25, 'Oak lactones are unique to American oak.'),
('bourbon', 'expert', 'What is the typical ester concentration in bourbon?', '20-80 mg/L', '["1-5 mg/L", "200-500 mg/L", "Over 1000 mg/L"]', 25, 'Esters contribute fruity characteristics.'),
('bourbon', 'expert', 'What federal agency regulates bourbon standards?', 'TTB (Alcohol and Tobacco Tax and Trade Bureau)', '["FDA", "USDA", "ATF only"]', 25, 'TTB sets and enforces bourbon standards.'),
('bourbon', 'expert', 'What is the Aldol condensation in bourbon aging?', 'Chemical reaction creating flavor compounds', '["Evaporation process", "Filtration method", "Fermentation stage"]', 25, 'Aldol reactions create complex flavors during aging.'),
('bourbon', 'expert', 'What is the Strecker degradation in bourbon production?', 'Amino acid breakdown creating aldehydes', '["Sugar fermentation", "Yeast reproduction", "Barrel breakdown"]', 25, 'Strecker degradation produces malty, bready notes.'),
('bourbon', 'expert', 'What temperature swing is optimal for bourbon aging in Kentucky?', '50-100°F annual range', '["10-20°F", "20-40°F", "Constant temperature"]', 25, 'Temperature fluctuation drives bourbon in and out of wood.'),
('bourbon', 'expert', 'What is the furfural content significance in bourbon?', 'Indicates heat treatment and age', '["Measures alcohol", "Determines color", "Tests for additives"]', 25, 'Furfural comes from heating hemicellulose in wood.'),
('bourbon', 'expert', 'What is the typical acetaldehyde level in bourbon?', '5-15 mg/L', '["0 mg/L", "100-200 mg/L", "500+ mg/L"]', 25, 'Acetaldehyde contributes green apple notes.'),
('bourbon', 'expert', 'What ratio of cis to trans oak lactones indicates American oak?', 'Higher cis (5:1 ratio)', '["Equal ratio", "Higher trans", "No trans present"]', 25, 'American oak has more cis-lactone than European oak.');
-- SCOTCH TRIVIA - 80 Questions
INSERT INTO bv_trivia_questions (category, difficulty, question, correct_answer, wrong_answers, proof_reward, explanation) VALUES
-- EASY (20)
('scotch', 'easy', 'What country produces Scotch whisky?', 'Scotland', '["Ireland", "England", "Wales"]', 10, 'Scotch must be made in Scotland by law.'),
('scotch', 'easy', 'How long must Scotch be aged minimum?', '3 years', '["1 year", "5 years", "10 years"]', 10, 'All Scotch must mature at least 3 years.'),
('scotch', 'easy', 'What grain is used in single malt Scotch?', 'Malted barley', '["Corn", "Wheat", "Rye"]', 10, 'Single malt uses 100% malted barley.'),
('scotch', 'easy', 'What gives Islay Scotch its smoky flavor?', 'Peat', '["Charcoal", "Oak", "Smoke injection"]', 10, 'Burning peat to dry barley creates smoke.'),
('scotch', 'easy', 'How is Scotch spelled (without the e)?', 'Whisky', '["Whiskey", "Whiskee", "Whiskie"]', 10, 'Scotland uses "whisky" spelling.'),
('scotch', 'easy', 'What is the most famous Scotch region for single malts?', 'Speyside', '["Islay", "Highland", "Lowland"]', 10, 'Speyside has the most distilleries.'),
('scotch', 'easy', 'What is Glenfiddich famous for being?', 'First single malt marketed globally', '["Oldest distillery", "Most expensive", "Only peated Speyside"]', 10, 'Glenfiddich pioneered single malt marketing.'),
('scotch', 'easy', 'What does "single malt" mean?', 'From one distillery', '["One barrel", "One year", "One batch"]', 10, 'Single refers to a single distillery source.'),
('scotch', 'easy', 'What color is most Scotch whisky?', 'Golden/amber', '["Clear", "Green", "Red"]', 10, 'Color comes from barrel aging and sometimes caramel.'),
('scotch', 'easy', 'What is a "dram"?', 'A serving of whisky', '["A bottle", "A barrel", "A distillery"]', 10, 'Dram is the traditional Scottish term.'),
('scotch', 'easy', 'What type of still is used for single malt Scotch?', 'Pot still', '["Column still", "Reflux still", "Continuous still"]', 10, 'Copper pot stills are traditional for single malt.'),
('scotch', 'easy', 'What island is famous for very peaty Scotch?', 'Islay', '["Skye", "Arran", "Mull"]', 10, 'Islay is known for intensely smoky whiskies.'),
('scotch', 'easy', 'What does "blended Scotch" contain?', 'Mix of malt and grain whiskies', '["Only single malts", "Only grain whisky", "Bourbon and Scotch"]', 10, 'Blends combine different whisky types.'),
('scotch', 'easy', 'What is the best-selling Scotch brand globally?', 'Johnnie Walker', '["Glenfiddich", "Macallan", "Chivas Regal"]', 10, 'Johnnie Walker leads global sales.'),
('scotch', 'easy', 'What shape are traditional Scotch whisky bottles?', 'Cylindrical/round', '["Square", "Triangular", "Hexagonal"]', 10, 'Round bottles are traditional.'),
('scotch', 'easy', 'What is "cask strength" Scotch?', 'Bottled at barrel proof without dilution', '["Aged in strongest barrels", "Highest alcohol possible", "Double distilled"]', 10, 'No water added after aging.'),
('scotch', 'easy', 'What river is important to many Speyside distilleries?', 'River Spey', '["River Thames", "River Clyde", "River Forth"]', 10, 'The Spey runs through the heart of whisky country.'),
('scotch', 'easy', 'What does "12 Year Old" on a bottle mean?', 'Youngest whisky in bottle is 12 years', '["Average age is 12", "Oldest is 12", "Exactly 12 years"]', 10, 'Age statement reflects the youngest component.'),
('scotch', 'easy', 'What is the main ingredient in Scotch besides barley?', 'Water', '["Sugar", "Yeast", "Hops"]', 10, 'Pure Scottish water is essential.'),
('scotch', 'easy', 'Which brand uses a striding man logo?', 'Johnnie Walker', '["Chivas Regal", "Ballantine''s", "Dewar''s"]', 10, 'The Striding Man has been used since 1908.'),
-- MEDIUM (35)
('scotch', 'medium', 'How many official Scotch whisky regions are there?', '5', '["3", "6", "8"]', 15, 'Highland, Lowland, Speyside, Islay, Campbeltown.'),
('scotch', 'medium', 'What does PPM measure in Scotch?', 'Phenol parts per million (peatiness)', '["Proof", "Production month", "Price per measure"]', 15, 'PPM indicates smoke level from peat.'),
('scotch', 'medium', 'What is "finishing" in Scotch production?', 'Secondary maturation in different casks', '["Final filtering", "Adding flavors", "Last distillation"]', 15, 'Finishing adds complexity from different wood.'),
('scotch', 'medium', 'What type of barrels does Macallan famously use?', 'Sherry casks', '["Bourbon barrels", "Port pipes", "Wine barrels"]', 15, 'Macallan is known for sherry cask maturation.'),
('scotch', 'medium', 'What is the "wash" in Scotch production?', 'Fermented liquid before distillation', '["Cleaning solution", "Final product", "Grain mixture"]', 10, 'Wash is essentially beer without hops.'),
('scotch', 'medium', 'Which region produces the lightest, most delicate Scotch?', 'Lowland', '["Islay", "Highland", "Campbeltown"]', 15, 'Lowland malts are typically gentle and grassy.'),
('scotch', 'medium', 'What is a "whisky loch"?', 'Warehouse for aging whisky', '["Lake near distillery", "Blending vat", "Water source"]', 15, 'Whisky lochs are maturation warehouses.'),
('scotch', 'medium', 'What makes Campbeltown Scotch distinctive?', 'Briny, maritime character', '["Extra peat", "No aging", "Column distilled"]', 15, 'Coastal location influences flavor.'),
('scotch', 'medium', 'What is "vatted malt" now called?', 'Blended malt', '["Single malt", "Grain whisky", "Pure malt"]', 15, 'Terminology changed in 2009.'),
('scotch', 'medium', 'Which Scotch brand features a ship on its label?', 'Cutty Sark', '["Famous Grouse", "Monkey Shoulder", "Johnnie Walker"]', 15, 'Named after the famous clipper ship.'),
('scotch', 'medium', 'What is the angel''s share in Scottish warehouses?', 'About 2% per year', '["0.5%", "5%", "10%"]', 15, 'Scotland''s climate causes slower evaporation.'),
('scotch', 'medium', 'What is "cold stabilization" in Scotch?', 'Chilling to remove haze-causing compounds', '["Freezing barrels", "Winter aging", "Ice filtration"]', 15, 'Also called chill filtration.'),
('scotch', 'medium', 'Which distillery is known for the tallest stills in Scotland?', 'Glenmorangie', '["Lagavulin", "Macallan", "Glenfiddich"]', 15, 'Tall stills produce lighter spirit.'),
('scotch', 'medium', 'What is "new make spirit"?', 'Freshly distilled, unaged whisky', '["New brand", "First batch", "Latest release"]', 15, 'Clear spirit before barrel aging.'),
('scotch', 'medium', 'What is the "cut" in Scotch distillation?', 'Selecting the heart of the distillate', '["Diluting", "Blending", "Filtering"]', 15, 'Stillman decides when to collect spirit.'),
('scotch', 'medium', 'Which whisky region has only 3 operating distilleries?', 'Campbeltown', '["Lowland", "Islay", "Speyside"]', 15, 'Once had 30+ distilleries.'),
('scotch', 'medium', 'What is "triple distillation" associated with in Scotland?', 'Auchentoshan distillery', '["All Scotch", "Islay only", "No Scottish distillery"]', 15, 'Auchentoshan is Scotland''s triple-distilled single malt.'),
('scotch', 'medium', 'What gives Highland Park its distinctive character?', 'Heather peat from Orkney', '["Mainland peat", "Seaweed", "No peat"]', 15, 'Orcadian heather peat is unique.'),
('scotch', 'medium', 'What is a "washback"?', 'Fermentation vessel', '["Distillation equipment", "Storage tank", "Bottling machine"]', 15, 'Where wash ferments before distilling.'),
('scotch', 'medium', 'What company owns the most Scotch distilleries?', 'Diageo', '["Pernod Ricard", "William Grant", "Beam Suntory"]', 15, 'Diageo owns 28+ Scotch distilleries.'),
('scotch', 'medium', 'What is "worm tub" condensation?', 'Traditional copper coil cooling method', '["Modern cooling", "Heating method", "Cleaning system"]', 15, 'Worm tubs create heavier spirit character.'),
('scotch', 'medium', 'Which island distillery uses seaweed in its process?', 'None officially, but Talisker has maritime notes', '["All island distilleries", "Bowmore", "Lagavulin"]', 15, 'Maritime location influences flavor, not ingredients.'),
('scotch', 'medium', 'What is the typical ABV of new make Scotch spirit?', '68-72%', '["40%", "50%", "94%"]', 15, 'Spirit is diluted before barreling.'),
('scotch', 'medium', 'What wood type is most common for Scotch aging?', 'Ex-bourbon American oak', '["New oak", "French oak", "Japanese oak"]', 15, 'Used bourbon barrels are most economical.'),
('scotch', 'medium', 'What is "Scotch whisky cake" or "spirit safe"?', 'Locked glass container for measuring distillate', '["Dessert", "Marketing term", "Barrel type"]', 15, 'HMRC requires locked spirit safes.'),
('scotch', 'medium', 'Which Japanese company owns several Scottish distilleries?', 'Suntory', '["Nikka", "Kirin", "Asahi"]', 15, 'Suntory owns Bowmore, Laphroaig, and more.'),
('scotch', 'medium', 'What is the floor malting process?', 'Traditional method of germinating barley on floors', '["Ground floor storage", "Concrete aging", "Bottom fermentation"]', 15, 'Few distilleries still floor malt.'),
('scotch', 'medium', 'Which Speyside distillery is known for Christmas cake flavors?', 'GlenDronach', '["Glenlivet", "Glenfiddich", "Glenmorangie"]', 15, 'Heavy sherry influence creates rich dried fruit notes.'),
('scotch', 'medium', 'What does "NAS" mean on Scotch bottles?', 'No Age Statement', '["New American Spirit", "Natural Aged Scotch", "Non-Alcoholic Spirit"]', 15, 'Age not disclosed on label.'),
('scotch', 'medium', 'What is the legal minimum bottling strength for Scotch?', '40% ABV', '["35%", "43%", "50%"]', 15, 'Cannot be bottled below 40% ABV.'),
('scotch', 'medium', 'Which distillery on Skye produces Talisker?', 'Talisker Distillery', '["Torabhaig", "None on Skye", "Multiple distilleries"]', 15, 'Until 2017, Talisker was Skye''s only distillery.'),
('scotch', 'medium', 'What is "whisky bond"?', 'Warehouse where duty hasn''t been paid', '["Financial instrument", "Adhesive", "Contract type"]', 15, 'Duty is paid when whisky leaves bond.'),
('scotch', 'medium', 'What is the "lyne arm" on a pot still?', 'Pipe connecting still to condenser', '["Handle", "Thermometer", "Valve"]', 15, 'Lyne arm angle affects spirit character.'),
('scotch', 'medium', 'Which region''s whiskies are often described as "smoky and medicinal"?', 'Islay', '["Speyside", "Highland", "Lowland"]', 15, 'Islay malts have distinctive peat character.'),
('scotch', 'medium', 'What is first-fill vs refill cask?', 'First use after original contents vs subsequent use', '["Quality grades", "Size differences", "Wood types"]', 15, 'First-fill imparts more flavor.'),
-- HARD (20)
('scotch', 'hard', 'What is the phenol level in heavily peated Scotch like Octomore?', 'Over 200 PPM', '["10-20 PPM", "50-80 PPM", "100-120 PPM"]', 20, 'Octomore is the world''s most heavily peated whisky.'),
('scotch', 'hard', 'What percentage of Scotch whisky is exported?', 'Over 90%', '["50%", "70%", "80%"]', 20, 'Scotland exports most of its whisky production.'),
('scotch', 'hard', 'What is the "draft" in Scotch production?', 'Spent grain after mashing', '["First pour", "Recipe", "Quality grade"]', 20, 'Draft is used for animal feed.'),
('scotch', 'hard', 'How many bottles of Scotch are exported per second?', 'About 40 bottles', '["5 bottles", "15 bottles", "100 bottles"]', 20, 'Approximately 1.2 billion bottles annually.'),
('scotch', 'hard', 'What is "pot ale"?', 'Liquid residue from first distillation', '["Beer style", "Container type", "Brand name"]', 20, 'Pot ale is processed for animal feed.'),
('scotch', 'hard', 'What enzyme is crucial in the mashing process?', 'Diastase (amylase)', '["Lactase", "Lipase", "Protease"]', 20, 'Converts starch to fermentable sugars.'),
('scotch', 'hard', 'What is the "middle cut" typically collected at?', '63-72% ABV', '["40-50% ABV", "80-90% ABV", "94%+ ABV"]', 20, 'Stillman determines exact cut points.'),
('scotch', 'hard', 'What Scottish island has the most distilleries per capita?', 'Islay', '["Skye", "Arran", "Orkney"]', 20, 'Islay has 9 distilleries for 3,000 people.'),
('scotch', 'hard', 'What is "rummager" in Scotch production?', 'Rotating arm preventing solids burning in still', '["Barrel roller", "Grain mixer", "Quality inspector"]', 20, 'Used in direct-fired stills.'),
('scotch', 'hard', 'What compound creates the "smoky bacon" note in peated whisky?', 'Guaiacol', '["Vanillin", "Eugenol", "Lactones"]', 20, 'Guaiacol comes from burning peat.'),
('scotch', 'hard', 'What is the typical fermentation time for Scotch?', '48-96 hours', '["12 hours", "24 hours", "1 week"]', 20, 'Longer fermentation creates more esters.'),
('scotch', 'hard', 'What is "feints" in distillation?', 'The tails portion recycled for redistillation', '["First runnings", "Best portion", "Waste product"]', 20, 'Feints are combined with low wines.'),
('scotch', 'hard', 'What water temperature is used for mashing?', '63-65°C', '["20°C", "100°C", "80°C"]', 20, 'Optimal temperature for enzyme activity.'),
('scotch', 'hard', 'How much barley makes one bottle of single malt?', 'About 1.4 kg', '["0.5 kg", "3 kg", "5 kg"]', 20, 'Considerable grain required per bottle.'),
('scotch', 'hard', 'What is "steep water" in malting?', 'Water for soaking barley to start germination', '["Cooling water", "Cleaning water", "Dilution water"]', 20, 'Steeping initiates the malting process.'),
('scotch', 'hard', 'What percentage of Scottish whisky is single malt vs grain?', 'About 10% single malt', '["50%", "30%", "70%"]', 20, 'Most production is grain whisky for blends.'),
('scotch', 'hard', 'What is the "green malt" stage?', 'Germinated barley before kilning', '["Unripe whisky", "Young whisky", "Grain type"]', 20, 'Green malt is dried to stop germination.'),
('scotch', 'hard', 'How many liters of water are needed per liter of whisky?', 'About 20 liters', '["2 liters", "5 liters", "50 liters"]', 20, 'Water usage is significant in production.'),
('scotch', 'hard', 'What is "spent lees"?', 'Residue from second distillation', '["Empty barrels", "Used yeast", "Old whisky"]', 20, 'Contains copper and is treated before disposal.'),
('scotch', 'hard', 'What specific gravity does wash reach before distillation?', '1.050-1.080 OG', '["1.000", "1.150", "1.200"]', 20, 'Original gravity indicates sugar content.'),
-- EXPERT (5)
('scotch', 'expert', 'What chemical compound causes "peat reek"?', 'Phenolic compounds especially cresols', '["Esters", "Aldehydes", "Ketones"]', 25, 'Cresols and xylenols from peat smoke.'),
('scotch', 'expert', 'What is the legal definition of Scotch regarding additives?', 'Only water and plain caramel coloring (E150a) allowed', '["No additives", "Any natural coloring", "Sugar allowed"]', 25, 'E150a is the only permitted additive.'),
('scotch', 'expert', 'What temperature kills enzymes during mashing?', 'Above 75°C', '["50°C", "60°C", "90°C"]', 25, 'Temperature control preserves enzyme activity.'),
('scotch', 'expert', 'What is the Scotch Whisky Regulations 2009?', 'Current legal framework governing Scotch', '["Marketing guideline", "Trade agreement", "Quality standard"]', 25, 'Defines what can legally be called Scotch.'),
('scotch', 'expert', 'What is the average cask loss over 12 years in Scotland?', '20-25%', '["5%", "40%", "50%"]', 25, 'Combined angel''s share and devil''s cut losses.');
-- IRISH WHISKEY - 40 Questions
INSERT INTO bv_trivia_questions (category, difficulty, question, correct_answer, wrong_answers, proof_reward, explanation) VALUES
('irish', 'easy', 'How many times is Irish whiskey typically distilled?', 'Three times', '["Once", "Twice", "Four times"]', 10, 'Triple distillation is traditional.'),
('irish', 'easy', 'What makes Irish whiskey smoother than Scotch?', 'Triple distillation', '["More sugar", "Longer aging", "Different grain"]', 10, 'Extra distillation removes harsh compounds.'),
('irish', 'easy', 'What is Ireland''s best-selling whiskey?', 'Jameson', '["Bushmills", "Redbreast", "Tullamore DEW"]', 10, 'Jameson dominates global Irish whiskey sales.'),
('irish', 'easy', 'How is Irish whiskey spelled?', 'With an "e" - whiskey', '["Without e - whisky", "Either way", "Whiskie"]', 10, 'Ireland uses "whiskey" spelling.'),
('irish', 'easy', 'What is the minimum aging for Irish whiskey?', '3 years', '["2 years", "5 years", "No minimum"]', 10, 'Same as Scotch, 3 years minimum.'),
('irish', 'medium', 'What is "single pot still" Irish whiskey?', 'Made from malted and unmalted barley in pot stills', '["Single barrel", "One distillation", "Small batch"]', 15, 'Unique to Ireland, uses mixed barley.'),
('irish', 'medium', 'Which is the oldest licensed distillery in the world?', 'Bushmills (1608)', '["Jameson", "Midleton", "Kilbeggan"]', 15, 'Bushmills was licensed in 1608.'),
('irish', 'medium', 'What distillery produces Redbreast?', 'Midleton', '["Bushmills", "Cooley", "Kilbeggan"]', 15, 'Midleton makes most Irish whiskey brands.'),
('irish', 'medium', 'What nearly killed the Irish whiskey industry?', 'Prohibition, trade wars, and Irish independence', '["World War I only", "Bad harvests", "Competition from Scotch"]', 15, 'Multiple factors devastated the industry.'),
('irish', 'medium', 'What is Tullamore DEW known for?', 'Triple distilled, triple blend', '["Oldest distillery", "Peat smoke", "Single barrel"]', 15, 'Combines grain, malt, and pot still whiskeys.'),
('irish', 'medium', 'What type of barrels does Irish whiskey typically age in?', 'Ex-bourbon and ex-sherry', '["New oak only", "Wine barrels only", "Steel tanks"]', 15, 'Used barrels are standard.'),
('irish', 'medium', 'What is "bonded" Irish whiskey?', 'Bottled in bond under government supervision', '["Glued barrels", "Blended", "Aged in warehouses"]', 15, 'Historical term for regulated production.'),
('irish', 'medium', 'Which county is considered the home of Irish whiskey?', 'Cork', '["Dublin", "Belfast", "Galway"]', 15, 'Midleton distillery is in Cork.'),
('irish', 'hard', 'What is "pure pot still" now called?', 'Single pot still', '["Single malt", "Blended", "Grain whiskey"]', 20, 'Terminology updated for clarity.'),
('irish', 'hard', 'How many distilleries operated in Ireland in 1900?', 'Over 30', '["5", "10", "88"]', 20, 'Industry contracted dramatically after.'),
('irish', 'hard', 'What is the typical unmalted barley ratio in pot still?', '30-60% unmalted', '["0%", "100%", "5-10%"]', 20, 'Mix of malted and unmalted is key.'),
('irish', 'hard', 'What caused Irish distillers to reject column stills initially?', 'Pride in traditional pot still methods', '["Cost", "Illegal", "No column stills existed"]', 20, 'This decision hurt competitiveness.'),
('irish', 'expert', 'What compound is higher in pot still vs single malt?', 'Pot still congeners and oils', '["Alcohol", "Water", "Sugar"]', 25, 'Unmalted barley creates different chemistry.'),

-- JAPANESE WHISKY - 40 Questions
('japanese', 'easy', 'When did whisky production begin in Japan?', '1920s', '["1800s", "1950s", "1990s"]', 10, 'Yamazaki opened in 1923.'),
('japanese', 'easy', 'Who founded Japan''s first whisky distillery?', 'Shinjiro Torii (Suntory)', '["Masataka Taketsuru", "Keizo Saji", "Ichiro Akuto"]', 10, 'Torii founded Suntory and Yamazaki.'),
('japanese', 'easy', 'What is Mizuwari?', 'Whisky with water and ice', '["Straight whisky", "Hot whisky", "Whisky cocktail"]', 10, 'Popular Japanese serving style.'),
('japanese', 'easy', 'Which company makes Hibiki?', 'Suntory', '["Nikka", "Kirin", "Mars"]', 10, 'Hibiki is Suntory''s premium blend.'),
('japanese', 'easy', 'What is a highball in Japan?', 'Whisky with soda water', '["Neat pour", "Whisky flight", "Aged whisky"]', 10, 'Highballs are extremely popular in Japan.'),
('japanese', 'medium', 'Who is called the father of Japanese whisky?', 'Masataka Taketsuru', '["Shinjiro Torii", "Keizo Saji", "Ichiro Akuto"]', 15, 'Taketsuru studied in Scotland, founded Nikka.'),
('japanese', 'medium', 'What wood is unique to Japanese whisky aging?', 'Mizunara (Japanese oak)', '["Bamboo", "Cherry", "Cedar"]', 15, 'Mizunara gives incense and sandalwood notes.'),
('japanese', 'medium', 'Why don''t Japanese distilleries trade barrels?', 'They are competitors, not collaborators', '["It''s illegal", "No transport", "Different sizes"]', 15, 'Unlike Scotland, no barrel sharing tradition.'),
('japanese', 'medium', 'What is Nikka''s signature distillery?', 'Yoichi', '["Yamazaki", "Hakushu", "Chichibu"]', 15, 'Yoichi uses coal-fired pot stills.'),
('japanese', 'medium', 'What does "Karuizawa" refer to in whisky?', 'A closed legendary distillery', '["A grain type", "An aging method", "A region"]', 15, 'Karuizawa closed in 2000, bottles are rare.'),
('japanese', 'medium', 'What style influenced Japanese whisky most?', 'Scottish single malt', '["American bourbon", "Irish whiskey", "Canadian whisky"]', 15, 'Taketsuru trained in Scotland.'),
('japanese', 'medium', 'What is the Coffey still used for at Nikka?', 'Making grain whisky', '["Malt whisky", "Filtering", "Heating"]', 15, 'Nikka Coffey Grain is highly regarded.'),
('japanese', 'hard', 'What year did Japanese whisky win "World''s Best"?', '2003 (Yamazaki 12)', '["1990", "2010", "2015"]', 20, 'First international recognition.'),
('japanese', 'hard', 'What percentage of Mizunara casks fail during production?', 'About 30%', '["5%", "10%", "50%"]', 20, 'Mizunara is difficult to work with.'),
('japanese', 'hard', 'What is "Ichiro''s Malt"?', 'Whisky from Chichibu by Ichiro Akuto', '["A blend", "Scotch import", "Grain whisky"]', 20, 'Akuto saved Hanyu stock and opened Chichibu.'),
('japanese', 'expert', 'What compound from Mizunara creates incense notes?', 'Coconut lactones and oriental wood compounds', '["Vanillin", "Tannins", "Esters"]', 25, 'Unique chemical profile from Mizunara.'),

-- TEQUILA - 40 Questions
('tequila', 'easy', 'What plant is tequila made from?', 'Blue agave', '["Cactus", "Corn", "Sugar cane"]', 10, 'Weber blue agave only.'),
('tequila', 'easy', 'What country must tequila be produced in?', 'Mexico', '["USA", "Spain", "Any country"]', 10, 'Tequila has geographical protection.'),
('tequila', 'easy', 'What is Blanco tequila?', 'Unaged or briefly aged clear tequila', '["Aged 5 years", "Gold colored", "Sweetened"]', 10, 'Blanco shows pure agave flavor.'),
('tequila', 'easy', 'What Mexican state produces most tequila?', 'Jalisco', '["Oaxaca", "Mexico City", "Chihuahua"]', 10, 'Jalisco is tequila''s heartland.'),
('tequila', 'easy', 'What is the worm in tequila bottles?', 'A myth - worms are in mezcal, not tequila', '["Required by law", "For flavor", "Quality indicator"]', 10, 'Marketing gimmick for some mezcals.'),
('tequila', 'medium', 'What is Reposado tequila?', 'Aged 2-12 months in oak', '["Unaged", "Aged 3+ years", "Double distilled"]', 15, 'Reposado means "rested."'),
('tequila', 'medium', 'What is Añejo tequila?', 'Aged 1-3 years', '["Unaged", "6 months", "5+ years"]', 15, 'Añejo means "aged."'),
('tequila', 'medium', 'What is Extra Añejo?', 'Aged more than 3 years', '["Extra alcohol", "Extra agave", "Double aged"]', 15, 'Category created in 2006.'),
('tequila', 'medium', 'What is a Jimador?', 'Skilled agave harvester', '["Distiller", "Blender", "Bottler"]', 15, 'Uses a coa tool to harvest.'),
('tequila', 'medium', 'How long does blue agave take to mature?', '6-10 years', '["1 year", "2-3 years", "15+ years"]', 15, 'Agave is not a quick crop.'),
('tequila', 'medium', 'What is the heart of the agave called?', 'Piña', '["Corazon", "Centro", "Core"]', 15, 'Piña means pineapple - similar appearance.'),
('tequila', 'medium', 'What is "100% agave" tequila?', 'Made entirely from blue agave sugars', '["Aged 100 months", "100 proof", "100 bottles"]', 15, 'Mixto tequila can use other sugars.'),
('tequila', 'hard', 'What is the traditional cooking method for agave?', 'Brick ovens (hornos)', '["Microwave", "Sun drying", "Boiling"]', 20, 'Slow cooking converts starches to sugars.'),
('tequila', 'hard', 'What is "diffuser" tequila production?', 'Industrial extraction using autoclaves', '["Traditional method", "Organic process", "Handmade"]', 20, 'Faster but controversial method.'),
('tequila', 'hard', 'What is the legal minimum agave sugar content for tequila?', '51% (for mixto)', '["25%", "75%", "100% always"]', 20, '100% agave is premium.'),
('tequila', 'expert', 'What chemical gives tequila its distinctive aroma?', 'Isoamyl alcohol and various esters', '["Ethanol only", "Agave oil", "Added flavoring"]', 25, 'Complex fermentation creates aromatics.'),

-- RUM - 30 Questions
('rum', 'easy', 'What is rum made from?', 'Sugar cane or molasses', '["Grain", "Grapes", "Potatoes"]', 10, 'Sugar-based spirit.'),
('rum', 'easy', 'What Caribbean nation is famous for rum?', 'Jamaica', '["Greenland", "Iceland", "Canada"]', 10, 'Jamaica has centuries of rum history.'),
('rum', 'easy', 'What color is white rum?', 'Clear', '["Brown", "Gold", "Green"]', 10, 'White rum is unaged or filtered.'),
('rum', 'easy', 'What is spiced rum?', 'Rum with added spices and flavors', '["Extra aged", "Higher proof", "Premium quality"]', 10, 'Popular flavored category.'),
('rum', 'medium', 'What is "rhum agricole"?', 'Rum made from fresh cane juice', '["Agricultural rum", "Organic rum", "Old rum"]', 15, 'French Caribbean style.'),
('rum', 'medium', 'What is the Solera aging system?', 'Fractional blending of different ages', '["Single barrel", "No aging", "Outdoor aging"]', 15, 'Creates consistent aged profile.'),
('rum', 'medium', 'Which country produces Havana Club?', 'Cuba', '["Puerto Rico", "Jamaica", "Barbados"]', 15, 'Famous Cuban rum brand.'),
('rum', 'medium', 'What is "navy strength" rum?', 'High proof rum (57%+ ABV)', '["Blue colored", "Ship-shaped bottle", "Sailor brand"]', 15, 'Proof that gunpowder still ignites.'),
('rum', 'hard', 'What is "dunder" in rum production?', 'Leftover liquid from distillation added to fermentation', '["Sugar type", "Barrel wood", "Yeast strain"]', 20, 'Creates Jamaican funk.'),
('rum', 'hard', 'What bacteria creates "hogo" in Jamaican rum?', 'Wild yeasts and bacteria during fermentation', '["Added culture", "No bacteria", "Mold"]', 20, 'Funky esters from open fermentation.'),
('rum', 'expert', 'What ester level defines "high ester" Jamaican rum?', 'Over 700 grams per hectoliter', '["100 g/hl", "200 g/hl", "400 g/hl"]', 25, 'Creates intense tropical fruit flavors.'),

-- GIN - 30 Questions  
('gin', 'easy', 'What is gin''s main botanical?', 'Juniper berries', '["Cucumber", "Lemon", "Rose"]', 10, 'Juniper defines gin.'),
('gin', 'easy', 'What country invented gin?', 'Netherlands', '["England", "France", "USA"]', 10, 'Genever was the original.'),
('gin', 'easy', 'What does "London Dry" mean?', 'A dry style, not sweetened after distillation', '["Made in London", "Extra dry taste", "No water"]', 10, 'Style, not geographical origin.'),
('gin', 'easy', 'What is the classic gin cocktail with vermouth?', 'Martini', '["Negroni", "Tom Collins", "Gimlet"]', 10, 'The iconic gin drink.'),
('gin', 'medium', 'What is "genever"?', 'Dutch/Belgian ancestor of gin', '["German gin", "Generic gin", "Gin brand"]', 15, 'Malt wine-based spirit.'),
('gin', 'medium', 'What is "bathtub gin"?', 'Homemade gin, often from Prohibition era', '["Bathroom-infused", "Premium small batch", "Low quality"]', 15, 'Made in bathtubs during Prohibition.'),
('gin', 'medium', 'What is Old Tom gin?', 'Slightly sweetened style of gin', '["Aged gin", "Strongest gin", "Clear gin"]', 15, 'Popular in 19th century.'),
('gin', 'medium', 'What cocktail uses gin, Campari, and sweet vermouth?', 'Negroni', '["Martini", "Gimlet", "Aviation"]', 15, 'Equal parts of each.'),
('gin', 'hard', 'What is "compound gin"?', 'Gin made by adding flavors without redistillation', '["Multiple botanicals", "Complex gin", "Premium gin"]', 20, 'Less refined production method.'),
('gin', 'hard', 'What defines "Navy Strength" gin?', '57% ABV or higher', '["Blue color", "Ship-related", "Military approved"]', 20, 'Would still ignite gunpowder.'),
('gin', 'expert', 'What is the key compound from juniper?', 'Alpha-pinene', '["Ethanol", "Vanillin", "Limonene"]', 25, 'Gives piney juniper character.'),

-- COGNAC - 25 Questions
('cognac', 'easy', 'What is Cognac made from?', 'Grapes (wine)', '["Grain", "Apples", "Sugar cane"]', 10, 'Double-distilled wine.'),
('cognac', 'easy', 'What country produces Cognac?', 'France', '["Spain", "Italy", "Portugal"]', 10, 'Cognac region of France only.'),
('cognac', 'easy', 'What does VS mean?', 'Very Special (2+ years)', '["Very Strong", "Vintage Select", "Very Smooth"]', 10, 'Minimum 2 years aging.'),
('cognac', 'easy', 'What does VSOP mean?', 'Very Superior Old Pale (4+ years)', '["Very Strong Old Pour", "Very Smooth Premium", "Vintage Special"]', 10, 'Minimum 4 years aging.'),
('cognac', 'easy', 'What does XO mean?', 'Extra Old (10+ years)', '["Extra Original", "Xtra Oaky", "Excellence Order"]', 10, 'Changed from 6 to 10 years in 2018.'),
('cognac', 'medium', 'What grape is most used in Cognac?', 'Ugni Blanc', '["Chardonnay", "Merlot", "Cabernet"]', 15, 'Also called Trebbiano.'),
('cognac', 'medium', 'What still type is used for Cognac?', 'Copper pot still (alembic)', '["Column still", "Reflux still", "Any still"]', 15, 'Traditional Charentais pot still.'),
('cognac', 'medium', 'How many times is Cognac distilled?', 'Twice', '["Once", "Three times", "Four times"]', 15, 'Double distillation required.'),
('cognac', 'medium', 'What are the premier Cognac growing regions?', 'Grande Champagne and Petite Champagne', '["Bordeaux", "Burgundy", "Loire"]', 15, 'Finest chalky soils.'),
('cognac', 'hard', 'What is "bonne chauffe"?', 'The second distillation in Cognac', '["Good heating", "Best barrel", "Premium grade"]', 20, 'Final distillation run.'),
('cognac', 'hard', 'What is the maximum distillation date for Cognac?', 'March 31 following harvest', '["December 31", "No limit", "June 30"]', 20, 'Strict production timeline.'),
('cognac', 'expert', 'What is "rancio" in aged Cognac?', 'Complex oxidized nutty flavor from long aging', '["Spoilage", "Off-flavor", "Barrel defect"]', 25, 'Desirable in old Cognacs.'),

-- GENERAL/PRODUCTION/HISTORY - 50 Questions
('general', 'easy', 'What does ABV stand for?', 'Alcohol By Volume', '["Aged Barrel Vintage", "American Beverage Value", "Alcohol Brew Volume"]', 10, 'Percentage of alcohol.'),
('general', 'easy', 'What is "proof" in alcohol?', 'Measure of alcohol content (US: 2x ABV)', '["Age", "Quality", "Price"]', 10, 'US proof = 2 times ABV.'),
('general', 'easy', 'What is "neat" whiskey?', 'Served straight without ice or water', '["Clean", "New", "Mixed"]', 10, 'Pure, unaltered pour.'),
('general', 'easy', 'What does "on the rocks" mean?', 'Served over ice', '["On a cliff", "Premium quality", "Straight up"]', 10, 'Ice cubes in the glass.'),
('general', 'easy', 'What glass is traditional for whiskey?', 'Rocks glass/tumbler', '["Wine glass", "Shot glass", "Champagne flute"]', 10, 'Also called old fashioned glass.'),
('general', 'medium', 'What is a Glencairn glass?', 'Tulip-shaped whisky tasting glass', '["Scottish brand", "Large tumbler", "Shot glass"]', 15, 'Designed for nosing whisky.'),
('general', 'medium', 'What is "cask strength"?', 'Bottled at barrel proof without dilution', '["Strongest available", "Barrel-flavored", "Premium grade"]', 15, 'No water added after aging.'),
('general', 'medium', 'What is "single barrel"?', 'From one individual barrel', '["One distillery", "One batch", "One ingredient"]', 15, 'Each bottle from same barrel.'),
('general', 'medium', 'What is "barrel proof"?', 'Same as cask strength', '["100 proof", "Highest proof", "Barrel-flavored"]', 15, 'Undiluted barrel strength.'),
('production', 'easy', 'What is fermentation?', 'Yeast converting sugar to alcohol', '["Aging", "Distillation", "Bottling"]', 10, 'Essential step in all spirits.'),
('production', 'easy', 'What is distillation?', 'Heating to separate alcohol from wash', '["Fermentation", "Aging", "Filtering"]', 10, 'Concentrates alcohol.'),
('production', 'medium', 'What is a "mash bill"?', 'Recipe of grains used', '["Price list", "Production schedule", "Barrel inventory"]', 15, 'Grain proportions in whiskey.'),
('production', 'medium', 'What is malting?', 'Germinating grain to create enzymes', '["Grinding", "Fermenting", "Distilling"]', 15, 'Converts starch to sugar.'),
('production', 'medium', 'What is the "wash" in spirits production?', 'Fermented liquid before distillation', '["Cleaning step", "Final product", "Water"]', 15, 'Essentially beer.'),
('production', 'hard', 'What is "reflux" in distillation?', 'Vapor condensing and falling back into still', '["Waste product", "Final output", "Yeast activity"]', 20, 'Creates lighter spirit.'),
('history', 'easy', 'What event ended American Prohibition?', '21st Amendment in 1933', '["World War II", "Civil War", "18th Amendment"]', 10, 'Prohibition lasted 13 years.'),
('history', 'medium', 'When did Prohibition begin in America?', '1920', '["1900", "1910", "1930"]', 15, '18th Amendment took effect.'),
('history', 'medium', 'What ancient civilization first distilled spirits?', 'Mesopotamians/Arabs', '["Greeks", "Romans", "Chinese"]', 15, 'Alembic still invented in Middle East.'),
('history', 'hard', 'What was the "whiskey tax" that caused the Whiskey Rebellion?', 'Federal excise tax on domestic spirits', '["Import tax", "State tax", "Sales tax"]', 20, '1791 tax sparked resistance.');
-- ADDITIONAL SPIRITS - 75 More Real Spirits
INSERT INTO bv_spirits (name, brand, category, country, region, distillery, proof, abv, age_statement, rarity, description, tasting_notes, msrp) VALUES
-- MORE BOURBON (20)
('Elijah Craig Small Batch', 'Elijah Craig', 'bourbon', 'USA', 'Kentucky', 'Heaven Hill', 94, 47, NULL, 'common', 'Named after the Baptist minister who invented bourbon.', '["vanilla", "caramel", "oak", "spice"]', 32.99),
('Knob Creek 9 Year', 'Knob Creek', 'bourbon', 'USA', 'Kentucky', 'Jim Beam', 100, 50, '9 years', 'common', 'Full-flavored, pre-Prohibition style bourbon.', '["maple", "oak", "vanilla", "nut"]', 36.99),
('Old Forester 1920', 'Old Forester', 'bourbon', 'USA', 'Kentucky', 'Brown-Forman', 115, 57.5, NULL, 'uncommon', 'Prohibition Style bourbon, bold and rich.', '["dark caramel", "chocolate", "spice"]', 59.99),
('Russell''s Reserve 10 Year', 'Wild Turkey', 'bourbon', 'USA', 'Kentucky', 'Wild Turkey', 90, 45, '10 years', 'uncommon', 'Hand-selected barrels by Jimmy and Eddie Russell.', '["vanilla", "caramel", "spice", "oak"]', 39.99),
('Evan Williams Single Barrel', 'Evan Williams', 'bourbon', 'USA', 'Kentucky', 'Heaven Hill', 86.6, 43.3, NULL, 'common', 'Vintage-dated single barrel bourbon.', '["honey", "apple", "oak"]', 29.99),
('Larceny Small Batch', 'Larceny', 'bourbon', 'USA', 'Kentucky', 'Heaven Hill', 92, 46, NULL, 'common', 'Wheated bourbon, smooth and sweet.', '["butterscotch", "honey", "bread"]', 27.99),
('Old Grand-Dad 114', 'Old Grand-Dad', 'bourbon', 'USA', 'Kentucky', 'Jim Beam', 114, 57, NULL, 'uncommon', 'High-rye bourbon with bold spice.', '["cinnamon", "caramel", "pepper"]', 29.99),
('Henry McKenna 10 Year BiB', 'Henry McKenna', 'bourbon', 'USA', 'Kentucky', 'Heaven Hill', 100, 50, '10 years', 'rare', 'Bottled in Bond single barrel.', '["vanilla", "caramel", "oak", "honey"]', 49.99),
('1792 Small Batch', '1792', 'bourbon', 'USA', 'Kentucky', 'Barton', 93.7, 46.85, NULL, 'common', 'Named for the year Kentucky became a state.', '["spice", "vanilla", "caramel"]', 32.99),
('Michter''s US*1 Bourbon', 'Michter''s', 'bourbon', 'USA', 'Kentucky', 'Michter''s', 91.4, 45.7, NULL, 'uncommon', 'Small batch, cost-no-object production.', '["caramel", "fruit", "vanilla"]', 44.99),
('Angel''s Envy Bourbon', 'Angel''s Envy', 'bourbon', 'USA', 'Kentucky', 'Louisville Distilling', 86.6, 43.3, NULL, 'uncommon', 'Port wine barrel finished bourbon.', '["vanilla", "raisins", "maple"]', 54.99),
('Basil Hayden''s', 'Basil Hayden''s', 'bourbon', 'USA', 'Kentucky', 'Jim Beam', 80, 40, NULL, 'common', 'Light, approachable high-rye bourbon.', '["pepper", "citrus", "tea"]', 42.99),
('Bulleit Bourbon', 'Bulleit', 'bourbon', 'USA', 'Kentucky', 'Four Roses', 90, 45, NULL, 'common', 'High-rye frontier whiskey style.', '["oak", "nutmeg", "pepper"]', 29.99),
('Jefferson''s Reserve', 'Jefferson''s', 'bourbon', 'USA', 'Kentucky', 'Kentucky Artisan', 90.2, 45.1, NULL, 'uncommon', 'Very small batch blend.', '["caramel", "spice", "oak"]', 49.99),
('Rebel Yell', 'Rebel', 'bourbon', 'USA', 'Kentucky', 'Lux Row', 80, 40, NULL, 'common', 'Wheated bourbon, formerly Rebel Yell.', '["vanilla", "caramel", "wheat"]', 19.99),
('Jim Beam Black', 'Jim Beam', 'bourbon', 'USA', 'Kentucky', 'Jim Beam', 86, 43, NULL, 'common', 'Extra-aged expression of Jim Beam.', '["caramel", "vanilla", "oak"]', 24.99),
('Very Old Barton BiB', 'Very Old Barton', 'bourbon', 'USA', 'Kentucky', 'Barton', 100, 50, NULL, 'common', 'Classic Bottled in Bond value bourbon.', '["corn", "caramel", "oak"]', 16.99),
('Early Times BiB', 'Early Times', 'bourbon', 'USA', 'Kentucky', 'Brown-Forman', 100, 50, NULL, 'common', 'Bottled in Bond version of classic brand.', '["vanilla", "caramel", "grain"]', 24.99),
('Wilderness Trail Bourbon', 'Wilderness Trail', 'bourbon', 'USA', 'Kentucky', 'Wilderness Trail', 100, 50, NULL, 'uncommon', 'Sweet mash craft distillery.', '["butterscotch", "vanilla", "spice"]', 54.99),
('New Riff Bourbon BiB', 'New Riff', 'bourbon', 'USA', 'Kentucky', 'New Riff', 100, 50, NULL, 'uncommon', 'Non-chill filtered, no additives.', '["caramel", "spice", "oak", "cherry"]', 44.99),

-- MORE SCOTCH (20)
('Ardbeg 10', 'Ardbeg', 'scotch', 'Scotland', 'Islay', 'Ardbeg', 92, 46, '10 years', 'uncommon', 'Intense peat with surprising sweetness.', '["peat smoke", "lemon", "pepper"]', 54.99),
('Talisker 10', 'Talisker', 'scotch', 'Scotland', 'Skye', 'Talisker', 91.6, 45.8, '10 years', 'uncommon', 'Maritime smoke and pepper.', '["smoke", "pepper", "sea salt"]', 64.99),
('Oban 14', 'Oban', 'scotch', 'Scotland', 'Highland', 'Oban', 86, 43, '14 years', 'uncommon', 'Gateway to the islands style.', '["orange", "sea salt", "honey"]', 79.99),
('Dalwhinnie 15', 'Dalwhinnie', 'scotch', 'Scotland', 'Highland', 'Dalwhinnie', 86, 43, '15 years', 'uncommon', 'Gentle and honeyed Highland malt.', '["heather", "honey", "vanilla"]', 74.99),
('Glenlivet 12', 'Glenlivet', 'scotch', 'Scotland', 'Speyside', 'Glenlivet', 80, 40, '12 years', 'common', 'Classic Speyside, fruity and floral.', '["pear", "apple", "vanilla"]', 44.99),
('Bowmore 12', 'Bowmore', 'scotch', 'Scotland', 'Islay', 'Bowmore', 80, 40, '12 years', 'uncommon', 'Balanced Islay peat and fruit.', '["smoke", "citrus", "honey"]', 54.99),
('Highland Park 12 Viking Honour', 'Highland Park', 'scotch', 'Scotland', 'Orkney', 'Highland Park', 86, 43, '12 years', 'uncommon', 'Heather peat and sherry sweetness.', '["heather", "honey", "smoke"]', 49.99),
('Caol Ila 12', 'Caol Ila', 'scotch', 'Scotland', 'Islay', 'Caol Ila', 86, 43, '12 years', 'uncommon', 'Lighter Islay style, smoky citrus.', '["smoke", "lemon", "oil"]', 64.99),
('Bunnahabhain 12', 'Bunnahabhain', 'scotch', 'Scotland', 'Islay', 'Bunnahabhain', 92.6, 46.3, '12 years', 'uncommon', 'Unpeated Islay, nutty and maritime.', '["sherry", "nuts", "sea salt"]', 54.99),
('Springbank 10', 'Springbank', 'scotch', 'Scotland', 'Campbeltown', 'Springbank', 92, 46, '10 years', 'rare', 'Complex Campbeltown character.', '["brine", "peat", "fruit"]', 69.99),
('Bruichladdich Classic Laddie', 'Bruichladdich', 'scotch', 'Scotland', 'Islay', 'Bruichladdich', 100, 50, NULL, 'uncommon', 'Unpeated Islay, terroir-driven.', '["barley", "citrus", "floral"]', 54.99),
('Aberlour 12 Double Cask', 'Aberlour', 'scotch', 'Scotland', 'Speyside', 'Aberlour', 80, 40, '12 years', 'common', 'Bourbon and sherry cask matured.', '["apple", "spice", "chocolate"]', 44.99),
('Auchentoshan 12', 'Auchentoshan', 'scotch', 'Scotland', 'Lowland', 'Auchentoshan', 80, 40, '12 years', 'common', 'Triple distilled Lowland malt.', '["citrus", "ginger", "vanilla"]', 44.99),
('Cragganmore 12', 'Cragganmore', 'scotch', 'Scotland', 'Speyside', 'Cragganmore', 80, 40, '12 years', 'uncommon', 'Complex, herbal Speyside.', '["smoke", "herbs", "honey"]', 54.99),
('Glen Grant 12', 'Glen Grant', 'scotch', 'Scotland', 'Speyside', 'Glen Grant', 86, 43, '12 years', 'common', 'Light and fruity Speyside.', '["apple", "almond", "vanilla"]', 39.99),
('Tomatin 12', 'Tomatin', 'scotch', 'Scotland', 'Highland', 'Tomatin', 86, 43, '12 years', 'common', 'Soft and fruity Highland.', '["apple", "spice", "oak"]', 34.99),
('AnCnoc 12', 'anCnoc', 'scotch', 'Scotland', 'Highland', 'Knockdhu', 80, 40, '12 years', 'common', 'Light Highland, honey and lemon.', '["honey", "lemon", "spice"]', 44.99),
('Cardhu 12', 'Cardhu', 'scotch', 'Scotland', 'Speyside', 'Cardhu', 80, 40, '12 years', 'common', 'Sweet and smooth Speyside.', '["pear", "honey", "malt"]', 54.99),
('Jura 10', 'Jura', 'scotch', 'Scotland', 'Island', 'Jura', 80, 40, '10 years', 'common', 'Island malt with light smoke.', '["oil", "honey", "coffee"]', 44.99),
('Kilchoman Machir Bay', 'Kilchoman', 'scotch', 'Scotland', 'Islay', 'Kilchoman', 92, 46, NULL, 'uncommon', 'Farm distillery, young peated Islay.', '["peat", "vanilla", "citrus"]', 64.99),

-- MORE IRISH (10)
('Powers Gold Label', 'Powers', 'irish', 'Ireland', NULL, 'Midleton', 86.4, 43.2, NULL, 'common', 'Traditional Dublin whiskey.', '["honey", "vanilla", "spice"]', 27.99),
('Writers'' Tears Copper Pot', 'Writers'' Tears', 'irish', 'Ireland', NULL, 'Walsh Whiskey', 80, 40, NULL, 'uncommon', 'Triple distilled pot still and malt.', '["honey", "vanilla", "ginger"]', 39.99),
('Bushmills 10', 'Bushmills', 'irish', 'Ireland', NULL, 'Old Bushmills', 80, 40, '10 years', 'common', 'Triple distilled single malt.', '["honey", "vanilla", "sherry"]', 44.99),
('Teeling Small Batch', 'Teeling', 'irish', 'Ireland', NULL, 'Teeling', 92, 46, NULL, 'uncommon', 'Rum cask finished blend.', '["vanilla", "spice", "rum"]', 34.99),
('Yellow Spot 12', 'Yellow Spot', 'irish', 'Ireland', NULL, 'Midleton', 92, 46, '12 years', 'rare', 'Malaga, sherry, and bourbon cask.', '["honey", "cream", "spice"]', 99.99),
('Kilbeggan', 'Kilbeggan', 'irish', 'Ireland', NULL, 'Kilbeggan', 80, 40, NULL, 'common', 'Double distilled Irish blend.', '["malt", "grain", "honey"]', 22.99),
('Connemara Peated', 'Connemara', 'irish', 'Ireland', NULL, 'Cooley', 80, 40, NULL, 'uncommon', 'Rare peated Irish single malt.', '["peat", "honey", "heather"]', 39.99),
('Method and Madness Single Pot', 'Method and Madness', 'irish', 'Ireland', NULL, 'Midleton', 92, 46, NULL, 'uncommon', 'Innovative pot still expression.', '["spice", "fruit", "wood"]', 54.99),
('Knappogue Castle 12', 'Knappogue Castle', 'irish', 'Ireland', NULL, 'Various', 80, 40, '12 years', 'uncommon', 'Single malt, bourbon cask.', '["vanilla", "honey", "citrus"]', 49.99),
('West Cork Bourbon Cask', 'West Cork', 'irish', 'Ireland', NULL, 'West Cork', 80, 40, NULL, 'common', 'Coastal Irish whiskey.', '["vanilla", "honey", "sea salt"]', 29.99),

-- MORE TEQUILA (10)
('Herradura Silver', 'Herradura', 'tequila', 'Mexico', 'Jalisco', 'Herradura', 80, 40, NULL, 'common', 'Estate-grown agave, 45 days rested.', '["agave", "citrus", "pepper"]', 44.99),
('El Tesoro Blanco', 'El Tesoro', 'tequila', 'Mexico', 'Jalisco', 'El Tesoro', 80, 40, NULL, 'uncommon', 'Tahona-crushed traditional style.', '["agave", "citrus", "mineral"]', 44.99),
('Fortaleza Blanco', 'Fortaleza', 'tequila', 'Mexico', 'Jalisco', 'Fortaleza', 80, 40, NULL, 'rare', 'Fifth-generation family distillery.', '["cooked agave", "citrus", "olive"]', 49.99),
('Espolon Reposado', 'Espolon', 'tequila', 'Mexico', 'Jalisco', 'Espolon', 80, 40, NULL, 'common', 'Lightly aged, bright and smooth.', '["agave", "vanilla", "caramel"]', 29.99),
('Casamigos Blanco', 'Casamigos', 'tequila', 'Mexico', 'Jalisco', 'Casamigos', 80, 40, NULL, 'common', 'Smooth ultra-premium tequila.', '["agave", "vanilla", "citrus"]', 49.99),
('Codigo 1530 Rosa', 'Codigo 1530', 'tequila', 'Mexico', 'Jalisco', 'Codigo', 80, 40, NULL, 'uncommon', 'Rested in red wine barrels.', '["agave", "berry", "vanilla"]', 59.99),
('Tequila Ocho Plata', 'Ocho', 'tequila', 'Mexico', 'Jalisco', 'Ocho', 80, 40, NULL, 'uncommon', 'Single estate vintage tequila.', '["agave", "citrus", "earth"]', 49.99),
('G4 Blanco', 'G4', 'tequila', 'Mexico', 'Jalisco', 'El Pandillo', 80, 40, NULL, 'rare', 'Small batch, traditional methods.', '["agave", "mineral", "citrus"]', 49.99),
('Siete Leguas Reposado', 'Siete Leguas', 'tequila', 'Mexico', 'Jalisco', 'Siete Leguas', 80, 40, NULL, 'uncommon', 'Traditional family distillery.', '["agave", "oak", "pepper"]', 54.99),
('Tapatio Blanco', 'Tapatio', 'tequila', 'Mexico', 'Jalisco', 'La Altena', 80, 40, NULL, 'uncommon', 'Classic Highland style.', '["agave", "citrus", "pepper"]', 39.99),

-- RUM, GIN, COGNAC, OTHER (15)
('Appleton Estate 12', 'Appleton', 'rum', 'Jamaica', NULL, 'Appleton', 86, 43, '12 years', 'uncommon', 'Rich Jamaican rum.', '["orange peel", "molasses", "spice"]', 34.99),
('Mount Gay XO', 'Mount Gay', 'rum', 'Barbados', NULL, 'Mount Gay', 86, 43, NULL, 'uncommon', 'World''s oldest rum brand.', '["banana", "vanilla", "almond"]', 49.99),
('Flor de Cana 12', 'Flor de Cana', 'rum', 'Nicaragua', NULL, 'Flor de Cana', 80, 40, '12 years', 'common', 'Slow-aged Nicaraguan rum.', '["vanilla", "caramel", "honey"]', 29.99),
('Plantation XO 20th Anniversary', 'Plantation', 'rum', 'Barbados', NULL, 'Plantation', 80, 40, NULL, 'uncommon', 'Cognac cask finished.', '["coconut", "vanilla", "spice"]', 54.99),
('Doorly''s 12', 'Doorly''s', 'rum', 'Barbados', NULL, 'Foursquare', 80, 40, '12 years', 'uncommon', 'Value-priced quality rum.', '["brown sugar", "vanilla", "spice"]', 29.99),
('Monkey 47 Gin', 'Monkey 47', 'gin', 'Germany', NULL, 'Black Forest', 94, 47, NULL, 'rare', '47 botanicals from Black Forest.', '["juniper", "citrus", "pepper", "floral"]', 44.99),
('The Botanist', 'Bruichladdich', 'gin', 'Scotland', 'Islay', 'Bruichladdich', 92, 46, NULL, 'uncommon', '22 Islay foraged botanicals.', '["juniper", "floral", "citrus", "herbs"]', 39.99),
('Sipsmith London Dry', 'Sipsmith', 'gin', 'England', NULL, 'Sipsmith', 83.2, 41.6, NULL, 'common', 'Craft London Dry revival.', '["juniper", "citrus", "coriander"]', 34.99),
('Plymouth Gin', 'Plymouth', 'gin', 'England', NULL, 'Plymouth', 82.4, 41.2, NULL, 'common', 'Protected geographic origin.', '["juniper", "earth", "citrus"]', 29.99),
('Aviation Gin', 'Aviation', 'gin', 'USA', NULL, 'Aviation', 84, 42, NULL, 'common', 'American New Western style.', '["lavender", "citrus", "juniper"]', 29.99),
('Courvoisier VS', 'Courvoisier', 'cognac', 'France', 'Cognac', 'Courvoisier', 80, 40, NULL, 'common', 'Smooth, fruity young Cognac.', '["fruit", "vanilla", "oak"]', 34.99),
('Pierre Ferrand 1840', 'Pierre Ferrand', 'cognac', 'France', 'Cognac', 'Pierre Ferrand', 90, 45, NULL, 'uncommon', 'Original Cognac formula recreation.', '["jasmine", "fig", "honey"]', 44.99),
('H by Hine VSOP', 'Hine', 'cognac', 'France', 'Cognac', 'Hine', 80, 40, NULL, 'uncommon', 'Light and floral style.', '["floral", "fruit", "spice"]', 54.99),
('Hakushu 12', 'Hakushu', 'japanese', 'Japan', NULL, 'Hakushu', 86, 43, '12 years', 'rare', 'Forest distillery, fresh and green.', '["green apple", "mint", "smoke"]', 149.99),
('Taketsuru Pure Malt', 'Nikka', 'japanese', 'Japan', NULL, 'Nikka', 86, 43, NULL, 'uncommon', 'Blend of Yoichi and Miyagikyo.', '["fruit", "malt", "spice"]', 69.99);

-- Verify counts
SELECT 'spirits' as table_name, count(*) as count FROM bv_spirits
UNION ALL
SELECT 'trivia_questions', count(*) FROM bv_trivia_questions
UNION ALL  
SELECT 'courses', count(*) FROM bv_courses
UNION ALL
SELECT 'rewards', count(*) FROM bv_rewards;

